### ISSUE TITLE
3.9.2: data loss on restart of master

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#342]
When cluster is fully replicated (no undergoal chunks) and all chunkservers are up I restart master. After restart of master there are new missing chunks in _std2_ goal.
It already happened at least twice. Interestingly missing chunks appear in files that recently had their goal changed from _xor2_ to _std2_.

Restarting master should not produce missing chunks.

**Comment by DarkHaze** [comment]
It might be the result if the chunkservers are pre 3.9.4 (http://cr.skytechnology.pl:8081/#/c/2287/). 
Otherwise it's most probably a bug. So If you could check chunkservers version I would be grateful.

**Comment by onlyjob** [comment]
Thank you. All chunkservers are 3.9.2 + most patches from "master". 3.9.4 is not released yet...

**Comment by onlyjob** [comment]
Damn, it happens on _every_ restart of master...  :(  :(
Could be related to https://github.com/lizardfs/lizardfs/commit/89e339a50fa10566e4c0309d49006c2c26c700c2 (see comments) and/or to #324.

**Comment by onlyjob** [comment]
Not sure if it is related but chunkservers occasionally log

~~~~
Dec 06 09:10:40 debness mfschunkserver[1278]: replication error: failed to create chunk (Chunk already exists)
Dec 06 09:10:40 debness mfschunkserver[1278]: replication error: failed to create chunk (Chunk already exists)
Dec 06 09:10:40 debness mfschunkserver[1278]: write_block_to_chunk: file:/var/lib/lizardfs/01/chunksFD/chunk_0000000007FD7E7F_00000001.liz - crc write error: EBADF (Bad file descriptor)
Dec 06 09:10:40 debness mfschunkserver[1278]: write_block_to_chunk: file:/var/lib/lizardfs/01/chunksFD/chunk_0000000007FD7E7F_00000001.liz - crc write error: EBADF (Bad file descriptor)
Dec 06 09:10:40 debness mfschunkserver[1278]: hdd_io_end: refcount = 0 - This should never happen!
~~~~

typically shortly after start of chunkserver.

**Comment by DarkHaze** [comment]
The issue should be fixed in commit 6b8932b83bcd33095325bf5ac35271c96bbf168e (chunkserver: Add handling of LIZ_CSTOMA_CHUNK_DAMAGED and LIZ_CSTOMA_CHUNK_LOST).
But you need to remember to update chunkservers as well. The problem was with invalid handling of chunks with the same id on one chunkserver.
After the update there might be missing chunk parts, but the system should be working properly from now on.

**Comment by onlyjob** [comment]
This is still happening, even with HEAD of master, after upgrading all chunkservers.
On first restart of master some new missing chunks were expected but on second restart new missing chunks appeared despite all new patches. As earlier, missing chunks appeared in files that recently had their goal changed from _xor2_ to _std2_ and both replicas were lost despite fully replicated state (no undergoal chunks) before master restart.

**Comment by onlyjob** [comment]
Problem seems to be with master as I specifically restarted chunkservers few times just to make sure that isolated restart of chunkserver is not responsible for new missing chunks.

**Comment by DarkHaze** [comment]
To tell you the truth I'm unable to reproduce this bug (and I'm talking about hundreds of restarts with different goal combinations/replications/strange goals). I've found small race condition in code registering chunks to master but I'm not really sure if this is responsible for this problem.
The fix is available here http://cr.skytechnology.pl:8081/#/c/2296/.

**Comment by onlyjob** [comment]
Thank you very much, @DarkHaze. Preliminary results of testing c2296 are good -- one restart of master so far produced no new missing chunks (which is a very first restart without loss of data). However previously I reproduced the problem by changing goal from _xor2_ to _std2_ on some files (and waiting for replication to complete) before restarting master. I'm going to do that after business hours today for final confirmation.

**Comment by onlyjob** [comment]
I'm pretty sure 99dfbdd fixed it. I'm unable to reproduce this issue any more.
Great job, @DarkHaze. :)
I lost ~900 files to that problem but now I'm re-gaining confidence in LizardFS.
Thank you.

**Comment by onlyjob** [comment]
Just restarted master in order to apply b131de1 and got ~2000 new missing chunks (_std2_).

Strangely enough new missing chunks are clustered in files that were converted from _xor2_ goal some days ago. That makes me wonder if garbage collection mistakenly deleted those chunks...
As far as I can see, all affected files are infrequently accessed and were never modified.
Total size of damaged files is around 400 GiB.

**Comment by psarna** [comment]
> That makes me wonder if garbage collection mistakenly deleted those chunks...

It **did**, prior to b131de1caa5fe582c90009eeb1f92e40ec0c6bf0. The missing chunks were unfortunately there all the time, but they weren't reported because of 3.9.2 misinterpretation of replication status for very specific combinations of goals and upgrades.

**Comment by onlyjob** [comment]
Maybe but I'm pretty sure at least some of those files were readable before restart.
Also those files had their goal changed twice (to _xor2_ then to _std2_) on 3.9.4...
I'll try to change goals with b131de1 and see how it goes.
