### ISSUE TITLE
3.10.2: serious performance regression

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#475]
Shortly after upgrade to 3.10.2 _master_ exhibited  serious performance regression with 100% CPU usage (one core) and _very slow_ response to clients, etc. Performance of the entire cluster is crippled. 

I couldn't find anything relevant in logs but my suspicion is that regression is somehow related to trash which is unusually big (8.1+ TiB; 1400000+ files). It looks like master struggles to remove files from trash and that it takes much longer than before so removing nightly snapshot ( `settrashtime -r 2`) created too much stress for _mfsmaster_.

Besides it appears that master uses main thread to process trash and that's one of the reasons why performance is affected so much...

**Comment by psarna** [comment]
Trash management was substantially changed in 3.10.2. Before that, some of the files were wrongfully not removed. So, it is possible that after upgrade a ton of files are suddenly eligible for removal - which could explain why master is busy with that.
In all previous versions, clearing the trash was an atomic operation, so removing 1400000 files at once would result in a huge freeze. Now the design is responsive and it assures that if master is busy with something for more than a short timeout (e.g. 1ms), it is yielded so clients and other things can be served. It definitely shouldn't cause slow responses from clients, chunkservers nor any other servers. Can you verify (via cgi or something) that trash files are indeed constantly being deleted and if the operation is fast?

Also, there are two flavours of trash management - with and without libJudy.so. libJudy version is faster. Is your 3.10.2 properly linked to libJudy (it is in all vendor packages and in all packages built on machines where libJudy is present. In your case, the packet is probably libjudydebian1)?

**Comment by onlyjob** [comment]
High CPU load manifested from the moment of taking snapshot and deleting an old one. Now number of files in trash are down to 4000 but constant high CPU load (100%) is still there and cluster performs terribly... :(
Just like previous release, new 3.10.2 binaries are linked with libjudy...
I'm running Debian packages as uploaded to "unstable".

**Comment by psarna** [comment]
Can you try to run `perf top`, or, even better `perf top -p $(pgrep mfsmaster)` and see what makes master so busy? Maybe it will give us more context...

PS
Release versions contain less symbols, but after installing our lizardfs-dbg.deb and adding it to perf with something like
~~~
for x in /usr/lib/debug/.build-id/*/*.debug; do perf buildid-cache -a $x; done
~~~
they should be recognized and so perf output would be more substantial (e.g. function names will be showed instead of their meaningless addresses).

**Comment by onlyjob** [comment]
Thanks for troubleshooting advise, @psarna. According to `perf top -p $(pgrep mfsmaster)` `TaskManager::Job::finalizeTask` uses around 86%...

**Comment by onlyjob** [comment]
All it takes to reproduce the problem is to `lizardfs setgoal -r 3` on directory with more than a 1_000_000+ files which returns the following error and set master to spend up to 95% of time in `TaskManager::Job::finalizeTask`:

    Can't read data from socket: timeout

Setting goals on smaller directories works but once it choke to set goal on sufficiently large tree (e.g. 3M files/dirs) all subsequent attempts to set goal fail with the same error (unless master is given some time to "cool down")... Restarting master helps. This problem is very easy/reliable to reproduce.

Also `setgoal` seems to choke on directory with 16378 files. After socket timeout master can recover if given enough time to cool down but second attempt to `setgoal` right after timeout is likely to throw master into endless loop with 100% CPU usage.

Also `getgoal` works very fast (and reliable) even on very large trees while `setgoal` struggles even  when there are no changes to goal... Perhaps one way to optimise `setgoal` is to check whether goal needs to be changed and update it only when required?

**Comment by DarkHaze** [comment]
Could you test commit 2710 (http://cr.skytechnology.pl:8081/#/c/2710/) ? It should solve the problem.

**Comment by onlyjob** [comment]
2710 is a big relief but `Can't read data from socket: timeout` still happens on user's home folders and 100% CPU utilisation and slowness are still there... I'll test further...

**Comment by onlyjob** [comment]
Socket timeouts are manifested even if there is no change to goal.

**Comment by DarkHaze** [comment]
@onlyjob Try commits 2710 + 2713. I think it should be working correctly now.

**Comment by onlyjob** [comment]
Thanks, I'll report back soon. :)

**Comment by onlyjob** [comment]
`settrashtime: invalid option -- 'l'`
30 seconds is a good timeout but on large folders 30 seconds is not enough.
I'd love to see "-l" option fixed...

**Comment by onlyjob** [comment]
__setgoal__ is much faster but still very limited without `-l` option and just 5 seconds timeout:

~~~~
# time lizardfs getgoal -r home/user
 files with goal        3 :      17809
 directories with goal  3 :     640616

real    0m0.151s
user    0m0.000s
sys     0m0.004s

# time lizardfs setgoal -r 3 home/user
Can't read data from socket: timeout

real    0m5.033s
user    0m0.000s
sys     0m0.004s
~~~~

Note that goal is not even changed in this example...

**Comment by DarkHaze** [comment]
Setgoal in patch 2712 has increased timeout and working -l option.

**Comment by DarkHaze** [comment]
After applying patches 2710 + 2711 + 2712 + 2713 we couldn't replicate performance degradation in master with settrashtime command. We tried system with millions of files with up to 20k files in one directory.
Due to changes in recursive operations there is much more data written to changelog (one entry for each changed inode instead of one entry for whole recursive operation). This makes whole operation much slower, but on our test system it was always less than 15s. 
But thanks to this approach master should be responsive all the time (even though top shows 100% CPU usage). Each recursive operation is now split into bits that cannot execute for more than 0.5ms. After this time operation is suspended and master checks if there are other requests to handle.

@onlyjob You could check what master is doing by looking at the end of changelog.mfs file. During recursive operation it will be appending SETTRASHTIME entries to changelog.

**Comment by onlyjob** [comment]
Thanks, @DarkHaze. With 2710 + 2711 + 2712 + 2713 recursive _setgoal_ and _settrashtime_ work well on large directories. Good work.

However another performance regression still exist: _makesnapshot_ became much slower in 3.10.2. Previously we were able to do snapshotting of some dirs in few minutes but now it takes hours and master spends all the time in `TaskManager::Job::finalizeTask` hence slowing down the whole cluster...
